import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import "leaflet/dist/leaflet.css";

import { Toaster } from "sonner";

const inter = Inter({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  style: ["normal"],
  variable: "--inter-font",
});

export const metadata: Metadata = {
  title: "Mapa do Brasil - GeoJSON",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br" className={`${inter.variable} light`}>
      <body>
        {children}

        <Toaster />
      </body>
    </html>
  );
}
